services:
  - type: web
    name: website-parsing-service
    runtime: python
    buildCommand: chmod +x build.sh start.sh && ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
